version: '3'
services:
  web:
    build: .
    command: npm start
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/app/server
      - /usr/app/server/node_modules/

    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
